- repo: local
  hooks:
  - id: licensing
    name: licensing
    entry: license-files
    language: python
    types: [file]
    require_serial: true
    verbose: true

  - id: black
    name: black
    entry: black
    language: python
    types: [python]
    require_serial: true

  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
    require_serial: true

  - id: mypy
    name: mypy
    entry: mypy -p {{ cookiecutter.python_module_name }}
    language: python
    types: [python]
    require_serial: true
    pass_filenames: false

  - id: pytest
    name: pytest
    entry: pytest -vvv
    language: python
    types: [python]
    pass_filenames: false
    always_run: true
