#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
[ProjectConfig]
# Only path variables can and must contain 'DIR', 'PATH' or 'ROOT' in their name as
# these tokens are used to identify path variables from other variable types.
PROJECT_ROOT = "."
PROJECT_NAME = "Mbed Build"
PROJECT_UUID = "b48f7f78-9c11-43e1-b162-2d7d4648708c"
PACKAGE_NAME = "mbed-build"
NEWS_DIR = "news/"
SOURCE_DIR = "mbed_build"
RELEASE_BRANCH_PATTERN = "^release.*$"
MODULE_TO_DOCUMENT = "mbed_build"
DOCUMENTATION_DEFAULT_OUTPUT_PATH = "local_docs"
DOCUMENTATION_PRODUCTION_OUTPUT_PATH = "docs"
VERSION_FILE_PATH = "mbed_build/_version.py"
CHANGELOG_FILE_PATH = "CHANGELOG.md"

[ProjectConfig.PACKAGES_WITH_CHECKED_LICENCE]
GitPython="BSD-3-Clause"
python-dotenv="BSD-3-Clause"
setuptools  = "MIT"
chardet = "LGPL-2.1 - Accepted temporarily"
pdoc3 = "AGPL-3.0 - Accepted temporarily"

[AutoVersionConfig]
CONFIG_NAME = "DEFAULT"
PRERELEASE_TOKEN = "beta"
BUILD_TOKEN = "dev"
TAG_TEMPLATE = "release/{version}"
targets = [ "mbed_build/_version.py",]

[AutoVersionConfig.key_aliases]
__version__ = "VERSION_KEY"
MAJOR = "major"
MINOR = "minor"
PATCH = "patch"
COMMIT = "COMMIT"

[AutoVersionConfig.trigger_patterns]
major = "news/*.major"
minor = "news/*.feature"
patch = "news/*.bugfix"

[tool.towncrier]
directory = "news"
filename = "CHANGELOG.md"
package = "mbed_build"
title_format = "{version} ({project_date})"
start_string = """
[//]: # (begin_release_notes)
"""

[[tool.towncrier.type]]
directory = "major"
name = "Major changes"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = false

[tool.black]
line-length = 120

[spdx]
CreatorWebsite = "spdx.org"
PathToSpdx = "spdx/spdxdocs"
UUID = "13762c7b-1d3d-4d22-9b37-8227ec4e7c3f"
