#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.2.0"
COMMIT = "cd6ed3e775dc422327c9b4849b6743d6346727cf"
MAJOR = 1
MINOR = 2
PATCH = 0
