#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.2.1"
COMMIT = "d21c711871502ea172fb0869d0ea88f9bcd37c5e"
MAJOR = 1
MINOR = 2
PATCH = 1
