#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.2.4"
COMMIT = "586a21188f2f4ef61968c75a8f5683695c191765"
MAJOR = 1
MINOR = 2
PATCH = 4
